#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  credentials:
    tanzuNet:
      host: registry.tanzu.vmware.com
      username: TANZUNET_USERNAME
      password: TANZUNET_PASSWORD
    registry:
      username: REGISTRY_USERNAME
      password: REGISTRY_PASSWORD
